run:
  timeout: 4m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
