name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install golangci-lint (compiled with same Go version)
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Format
        run: make fmt

      - name: Vet
        run: make vet

      - name: Lint
        run: make lint

      - name: Build
        run: make build
